"""Export an MLflow experiment's runs table to CSV + markdown under data/03_shared/runs/.

The local MLflow store (sqlite:///mlflow.db) is not visible to reviewers of
this repo. This script serializes the runs table two ways:

  - {experiment}_runs.csv   Full dump. Data artifact — every param, metric,
                            and tag. For anyone who wants to sort/filter
                            in a spreadsheet or diff the raw numbers.
  - {experiment}_runs.md    Curated summary table with 8 columns rendered
                            as GitHub-flavored markdown. Reading artifact
                            — this is what a reviewer actually opens.

Timestamps become ISO strings. `artifact_uri` is dropped from the CSV
because it embeds the user's absolute home path.

Usage:
    .venv/bin/python scripts/export_mlflow_runs.py
    .venv/bin/python scripts/export_mlflow_runs.py --experiment lora-training
    .venv/bin/python scripts/export_mlflow_runs.py --output somewhere/else.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path

import mlflow
import pandas as pd
from loguru import logger

from fashion_forensics.config import PROJECT_ROOT, settings

DEFAULT_EXPERIMENT = "trend-classifier-eval"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "03_shared" / "runs"

# Short, human-readable names for HF model IDs. Anything not listed falls
# back to the last path component (e.g. "some-org/foo-bar" -> "foo-bar").
MODEL_SHORT_NAMES = {
    "patrickjohncyh/fashion-clip": "fashion-CLIP",
    "openai/clip-vit-base-patch32": "vanilla-CLIP",
}


def _short_model(name: str | float) -> str:
    if not isinstance(name, str) or not name:
        return ""
    return MODEL_SHORT_NAMES.get(name, name.rsplit("/", 1)[-1])


def _fmt_metric(row: pd.Series, base: str) -> str:
    """Render a metric as 'point [lo, hi]' if bootstrap CIs exist, else just 'point'."""
    point = row.get(f"metrics.{base}")
    if pd.isna(point):
        return ""
    lo = row.get(f"metrics.{base}_bootstrap_lo")
    hi = row.get(f"metrics.{base}_bootstrap_hi")
    if pd.notna(lo) and pd.notna(hi):
        return f"{point:.3f} [{lo:.3f}, {hi:.3f}]"
    return f"{point:.3f}"


def _fmt_alpha(row: pd.Series) -> str:
    mode = row.get("params.search_mode")
    alpha = row.get("params.alpha")
    if mode != "hybrid" or pd.isna(alpha):
        return ""
    return f"{float(alpha):.2f}"


def _render_md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a GitHub-flavored markdown table without the tabulate dependency."""
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _build_markdown_summary(df: pd.DataFrame, experiment_name: str) -> str:
    """Curate the full runs frame down to a GitHub-renderable summary table."""
    headers = [
        "run_id",
        "date",
        "model",
        "mode",
        "alpha",
        "n_refs",
        "accuracy (95% CI when bootstrapped)",
        "macro F1",
        "ECE",
    ]
    body: list[list[str]] = []
    for _, row in df.iterrows():
        n_refs = row.get("params.n_refs")
        n_refs_str = "" if pd.isna(n_refs) else str(int(float(n_refs)))
        body.append(
            [
                str(row.get("run_id", ""))[:8],
                str(row.get("start_time", ""))[:10],
                _short_model(row.get("params.embedding_model")),
                str(row.get("params.search_mode", "") or ""),
                _fmt_alpha(row),
                n_refs_str,
                _fmt_metric(row, "accuracy"),
                _fmt_metric(row, "macro_f1"),
                _fmt_metric(row, "ece"),
            ]
        )
    body.sort(key=lambda r: r[1], reverse=True)

    header = (
        f"# MLflow runs: `{experiment_name}`\n\n"
        f"Curated summary of {len(body)} runs from the local MLflow store, "
        "generated by `scripts/export_mlflow_runs.py`. Full data (all params, "
        f"per-class metrics, tags) is in `{experiment_name}_runs.csv` alongside "
        "this file.\n\n"
        "Metric cells show `point [lo, hi]` when bootstrap CIs were logged, "
        "otherwise just the point estimate. Empty cells mean the run did not "
        "log that value.\n\n"
    )
    return header + _render_md_table(headers, body) + "\n"


def export_runs(experiment_name: str, csv_path: Path) -> int:
    """Serialize an experiment's runs table to CSV + markdown. Returns row count."""
    mlflow.set_tracking_uri(settings.mlflow_tracking_uri)
    logger.info(f"MLflow tracking URI: {settings.mlflow_tracking_uri}")
    logger.info(f"Experiment: {experiment_name}")

    df = mlflow.search_runs(experiment_names=[experiment_name])
    if df.empty:
        logger.warning(f"No runs found for experiment '{experiment_name}' — nothing to export")
        return 0

    # Convert epoch-ms timestamps to ISO strings so the CSV is human-readable.
    for col in ("start_time", "end_time"):
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], utc=True).dt.strftime("%Y-%m-%dT%H:%M:%SZ")

    # artifact_uri embeds an absolute local path (leaks the user's home dir).
    df = df.drop(columns=[c for c in ["artifact_uri"] if c in df.columns])

    # MLflow returns columns in non-deterministic order (dict iteration).
    # Sort them so regenerating the CSV doesn't produce spurious diffs.
    id_cols = ["run_id", "experiment_id", "status", "start_time", "end_time"]
    id_cols = [c for c in id_cols if c in df.columns]
    other_cols = sorted(c for c in df.columns if c not in id_cols)
    df = df[id_cols + other_cols]

    csv_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(csv_path, index=False)
    logger.info(
        f"Wrote {len(df)} runs to {csv_path.relative_to(PROJECT_ROOT)} "
        f"({csv_path.stat().st_size:,} bytes, {len(df.columns)} columns)"
    )

    md_path = csv_path.with_suffix(".md")
    md_path.write_text(_build_markdown_summary(df, experiment_name))
    logger.info(
        f"Wrote markdown summary to {md_path.relative_to(PROJECT_ROOT)} "
        f"({md_path.stat().st_size:,} bytes)"
    )
    return len(df)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--experiment",
        default=DEFAULT_EXPERIMENT,
        help=f"MLflow experiment name (default: {DEFAULT_EXPERIMENT})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            f"Output CSV path (default: {DEFAULT_OUTPUT_DIR.relative_to(PROJECT_ROOT)}/"
            "{experiment}_runs.csv). The markdown summary is written next to it "
            "with a .md extension."
        ),
    )
    args = parser.parse_args()

    out = args.output or DEFAULT_OUTPUT_DIR / f"{args.experiment}_runs.csv"
    export_runs(args.experiment, out)
